### ISSUE TITLE
Weirdness with NeoVars

### ISSUE THREAD

**Issue by Boddlnagg** [neo-layout/neo-layout#11]
I've been a user of NeoVars for over ten years now, but every now and then, NeoVars freaks out and does weird things, such as locking the Alt key (which should not even be possible with Neo). I usually "fix" this by randomly smashing L/R Alt, Ctrl and Shift keys and ending up in a situation where Alt is no longer locked, but instead Shift is, which I can fix by pressing Shift L+R.

Am I the only one with these problems? Does anyone know how to prevent it from happening or how to fix it?

**Comment by reminiscience** [comment]
I have this problem, too. It's very annoying.

**Comment by ultimanet** [comment]
Exactly the same for me. 
Additionally, if in a Windows RDP Session Shift Lock is pressed, a R-Alt lock gets toggled.

**Comment by Tragetaschen** [comment]
I have definitely seen this as well. The thing I noted is that after moving from a thermal-throttled, mobile processor to a Xeon workstation, the chances of this happening has been drastically reduced.

**Comment by qwertfisch** [comment]
Hallo an alle,

der Issues-Bereich hier wird demnächst geschlossen, zugunsten des [offiziellen Issuetrackers](https://git.neo-layout.org/neo/neo-layout). Wenn dieses Issue weiterhin relevant ist, eröffnet bitte ein neues dort.

Falls ihr dort noch nicht registriert seid, kann man sich auch direkt über den Github-Account [anmelden](https://git.neo-layout.org/user/oauth2/github).

**Comment by Boddlnagg** [comment]
Habe dort ein neues [Issue](https://git.neo-layout.org/neo/neo-layout/issues/537) aufgemacht.
