### ISSUE TITLE
Level 3 not working in MS Edge

### ISSUE THREAD

**Issue by andypillip** [neo-layout/neo-layout#12]
Anybody else got that issue?

I installed the layout in Windows, I'm not using the autohotkeys.
In Internet Explorer everything is fine, but in Edge I cannot use Level 3.

Anybody else got that issue and knows a way to work around it?

**Comment by doncatnip** [comment]
Yes: don't use edge. Sorry, I could not resist ...
Microsoft products seem to behave very weird. In skype for example, you cannot use any layer other than shift whatsoever.

**Comment by JBenda** [comment]
This is because edge is a UWP-App, and the UWP VM has the bug that only the "normal" Layers are supported, ther is a Ticket by microsoft, I will link it if i find it.

So work around is: use Firefox or Chrom


(UWP = Universal Windows Platorm Aplication)

**Comment by joschkaschoener** [comment]
I recently switched to the autohotkey solution because of this incompatibitility of several applications. Also buggy but less annoying..

**Comment by JBenda** [comment]
The corresponding [issue](https://github.com/microsoft/microsoft-ui-xaml/issues/588) is marked as fixed, now we wait for the update.

**Comment by JBenda** [comment]
I tested the insider build and it's finally works :) it should be shipped with the spring update according to the Microsoft support.

**Comment by qwertfisch** [comment]
Also works in the final release of Windows 10 (2004).
