### ISSUE TITLE
Shift+left arrow (M4) not working

### ISSUE THREAD

**Issue by nspiller** [neo-layout/neo-layout#14]
The key combination `Shift` + `M4` + `s` (`Shift` + `left arrow`) does not produce any detectable input. It should select text towards the left character-wise.

The other arrow keys on level 4 are working as expected. Keystroke detection via `xev` does not record any input. 

I am using the layout on Ubuntu 18.04.

**Comment by HenningJW** [comment]
Can you check if your keyboard can detect all three keys pressed at once? Lots of keyboards can't detect some three key combinations.

**Comment by nspiller** [comment]
You were right, it is only not working with the external keyboard – laptop is working.
Thanks!
