### ISSUE TITLE
Stuck on layer 4 with only one mod4 key

### ISSUE THREAD

**Issue by laolux** [neo-layout/neo-layout#16]
Hey, sorry for posting here as the problem might be with gnome and not neo layout.
First off, neo2 is great and I love using is, so thanks a lot.

Now to the issue at hand:
My computer just switched hard to layer 4, as if both mod4 keys have been pressed simultaneously. Problem is I did not do it. And I do not know how to switch back, as I only have one mod4 key (right Alt). I tried restarting my computer, tried removing neo2 from the available layouts, but nothing worked. Does anyone have an idea of which gnome setting to change to get neo2 back to default? Or how to input both mod4 under linux with only one mod4 key available?
Many thanks!

**Comment by doncatnip** [comment]
You are still on layer 4 even after switching to a different keyboard layout ? I wonder how that is even possible, since pretty much no other layout should have a layer 4 ... Does that mean the right alt key is stuck on a different layout ? I suppose you ruled out hardware issues ? Some fancy programmable keyboard that can have a hardware toggle ?

**Comment by laolux** [comment]
Sorry for being imprecise. When switch to lets say regular english keyboard layout that just works fine. However, when I switch back to neo2 then I immediately have layer 4 again. So for now I use qwerty, but that obviously sucks, I want to use the great neo2 again. My keyboard is very basic, nothing fancy, oly a bit old and withou "<>|" key.

**Comment by doncatnip** [comment]
That's quite strange. It never happened to me and I use neo + linux for more than 10 years now. How do you configure it ? There are different ways. I used to have some problems when using command lines during xinit. I'm now using a quite simple xorg config:

/etc/X11/xorg.conf.d/90-keytable.conf

    Section "InputClass"
        Identifier "LocalKeyboard"
        Option  "XkbLayout"     "de"
        Option  "XkbVariant"    "neo"
    EndSection

Maybe this helps.

**Comment by laolux** [comment]
Yes, indeed very strange. Especially because that never happened on my laptop in three years using neo2, only on this new machine. Also, on this new machine this problem is now occurring for the third time. The first two I fixed by borrowing a keyboard from a friend, but that's always a bit cumbersome.
As for the setup, I just went to gnome settings, region & language and then add neo2 as input source.

I think what would help would be to remap the print key to be mod4. Unfortunately I do not know how to do that... Any suggestions?

**Comment by doncatnip** [comment]
You can remap keys with xmodmap. Something like

    keycode 51 = Alt_R

You'll have to find the correct keycode using xev - in arch it's the package xorg-xev.

**Comment by laolux** [comment]
Thanks a lot, that solved my problem! I used

    xmodmap -e "keycode 78 = ISO_Level5_Lock"

to map the scroll lock key to <>|. Then I used both mod4 keys (right alt and scroll lock) to come back to regular neo2 layer 1. Only caveat: I had to switch to gnome on xorg to do so, xmodmap does not work on wayland.
