### ISSUE TITLE
One Hand Mode in Linux?

### ISSUE THREAD

**Issue by martinfelis** [neo-layout/neo-layout#17]
Is the the one hand mode supported under Linux?

I got the one hand mode (Einhandmodus) running on Windows using neo-vars/out/neo20.exe and then M3+F10 running. However under Linux (Ubuntu 18.04) this shortcut was not working.

**Comment by martinfelis** [comment]
I was able to help myself using a customization of https://github.com/kbingham/xhk. For anyone interested you can find the changes here: https://github.com/martinfelis/xhk

**Comment by exic** [comment]
Is there any documentation about one hand mode? I've never read about that, is it a native neo thing or is it about http://www.onehandkeyboard.org/ mentioned in the project you linked? I find the idea quite interesting and would like to check if I like to use it.
