### ISSUE TITLE
Is there an easy way to install Neo on Windows

### ISSUE THREAD

**Issue by escamoteur** [neo-layout/neo-layout#19]
Hi,

I stumbled over Neo while researching keyboard layouts for programming. Unfortunately the setup.exe can't be executed on a current Windows 10 machine.
Is there any driver for Windows 10 available at all?

Cheers
Thomas

**Comment by theAkito** [comment]
Looking for [this](https://neo-layout.org/neo20.exe)?

The homepage design is really bad. It took me a while to find the download button more than once, already.

**Comment by escamoteur** [comment]
Thanks a lot, I wasn't able to find it. Hope they revive this project so that you also get an installable driver.

**Comment by escamoteur** [comment]
You really have to know that this are download links. Thanks again.

**Comment by escamoteur** [comment]
I leave it open so it does get forgotten

**Comment by qwertfisch** [comment]
Hallo @escamoteur,

der Issues-Bereich hier wird demnächst geschlossen, zugunsten des [offiziellen Issuetrackers](https://git.neo-layout.org/neo/neo-layout). Wenn dieses Issue weiterhin relevant ist, eröffne bitte ein neues dort. (Es wird bald eine neue Homepage geben, auf der die Downloads deutlich einfacher zu finden sind.)

Falls Du dort noch nicht registriert bist, kannst Du dich auch direkt über den Github-Account [anmelden](https://git.neo-layout.org/user/login).
