### ISSUE TITLE
Shift Key with „Stickey Keys“ enabled

### ISSUE THREAD

**Issue by ZarthKa** [neo-layout/neo-layout#20]
Hi there,

I use neo2 always from a few month ago. I have „Sticky Keys“ enabled to help me handiling the keyboard with one hard. Sticky Keys is a accessibility feature in KDE and other environments.

On my Manjaro Notebook I encounter the problem, that when I press Shift-Key twice and release it to lock Shift-Key, the first entered letter is always lowercase, like so (Shift Key locked) uIAEO. All the letters afterwards are correctly in uppercase. And when I unlock Shift by pressing Shift-Key twice, the first character is still uppercase. Then it continues as it should with all the characters lowercase.

When I lock mod3 there is no problem. The characters are all Mod3-style from the start, like so (Mod3 locked) ?**(
I can unlock mod3 by pressing it just once.

Is there a way to lock Shift with all characters uppercase immediately and to unlock it by pressing it just once? 

Regards

Karsten

**Comment by qwertfisch** [comment]
Hallo @ZarthKa,

der Issues-Bereich hier wird demnächst geschlossen, zugunsten des [offiziellen Issuetrackers](https://git.neo-layout.org/neo/neo-layout). Wenn dieses Issue weiterhin relevant ist, eröffne bitte ein neues dort. 

Falls Du dort noch nicht registriert bist, kannst Du dich auch direkt über den Github-Account [anmelden](https://git.neo-layout.org/user/oauth2/github). Dabei wird ein Gitea-Account mit demselben Namen automatisch angelegt.
