### ISSUE TITLE
Compatibility problem with the Windows key+v

### ISSUE THREAD

**Issue by escamoteur** [neo-layout/neo-layout#21]
Hi,
first of all I want to tell you that I really love Neo2!
Today I found a problem with the new multi clipboard feature of Windows 10.
When I press Win+v the dialog opens but it closes directly when I release the keys so I have no chance to select anything.
As this is a function that I really use all the all the time it would be awesome if someone could look into this.

**Comment by Boddlnagg** [comment]
I noticed the same thing. I was already using Neo before learning about the new multi clipboard, so it never bothered me much that it doesn't work, because I just never used the multi clipboard. But a fix would be much appreciated!

**Comment by reminiscience** [comment]
I would like to recommend Clipjump, it's very powerful and it works with Neo (but it has to be loaded AFTER Neo).

**Comment by qwertfisch** [comment]
The issue seems to be resolved when using Windows 10 (2004), which was released on May 27th. Possible that this was related to https://github.com/neo-layout/neo-layout/issues/12.
