### ISSUE TITLE
Falscher Layoutstring, zu wenige Zeichen!

### ISSUE THREAD

**Issue by 0bstinate** [neo-layout/neo-layout#22]
Sobald ich eine Neo2.ini anlege und einen customLayout verwende bekomme ich eine Fehlermeldung

Im Pfad neo-layout/windows/neo-vars/src/keydefinitions.ahk
 
ab Zeile 194 wird auf 33 Zeichen abgeprüft.

Change1256Layout(newlayoutstring) {
  global
  if (strlen(newlayoutstring) != 33) {
    MsgBox,Falscher Layoutstring, zu wenige Zeichen!
    return
  }

Ich habe folgenden (adnw) String verwendet: "-jduaxphlmwßctieobnrsgqfvüäöyz,.k"
Die Meldung kommt aber auch bei dem im Wiki angegebenem String für Neo2 : 
"-xvlcwkhgfqßuiaeosnrtdyüöäpzbm,.j" beide haben 33 Zeichen. Ich kann nicht sagen was "strlen" zurückgibt oder ob etwas falsches übergeben wird habe (ohne die Programmiersprache zu kennen) keine Fehler gefunden.  

Anmerkung: die Meldung kann irreführend sein falls man zu viele Zeichen verwenden würde

**Comment by doncatnip** [comment]
AHK Entwickler haben wohl die letzten 20 jahre verpennt. Speicher das script in dem newlayoutstring definiert wird mit ANSI (windows-1252) encoding statt UTF 8 und es funktioniert.

**Comment by 0bstinate** [comment]
Danke, jetzt funktioniert es

**Comment by qwertfisch** [comment]
Das Problem scheint gelöst zu sein. Ich schließe es daher und verweise auf den [offiziellen Issuetracker](https://git.neo-layout.org/neo/neo-layout), falls weitere Probleme auftreten.

Der Issue-Bereich hier auf GitHub wird demnächst geschlossen.
