### ISSUE TITLE
Smilie-Ebene

### ISSUE THREAD

**Issue by fbruetting** [neo-layout/neo-layout#6]
Könnte eine zusätzliche Ebene für Smilies eingeführt werden? Fände ich sehr sinnvoll! :)

**Comment by qwertfisch** [comment]
Hallo @fbruetting 

Der Issues-Bereich hier wird demnächst geschlossen, zugunsten des [offiziellen Issuetrackers](https://git.neo-layout.org/neo/neo-layout). Wenn dieses Issue weiterhin relevant ist, eröffne bitte ein neues dort.

Falls Du dort noch nicht registriert bist, kannst Du dich auch direkt über deinen Github-Account [anmelden](https://git.neo-layout.org/user/oauth2/github).
